### ISSUE TITLE
请求sql文件

### ISSUE THREAD

**Issue by CrushDemo01** [TouwaErioer/shuttle#4]
您好，您的项目非常棒！
我想尝试运行它。但我只会一点Spring boot和基础的vue，导致我有些看不懂。
我想向您请求相关的数据库文件，以便我能尝试自己运行其这个项目。
感谢！

**Comment by TouwaErioer** [comment]
SQL 文件：https://github.com/TouwaErioer/shuttle/blob/master/init/mysql/shuttle.sql

**Comment by cool012** [comment]
> 您好，您的项目非常棒！ 我想尝试运行它。但我只会一点Spring boot和基础的vue，导致我有些看不懂。 我想向您请求相关的数据库文件，以便我能尝试自己运行其这个项目。 感谢！

SQL 文件：https://github.com/TouwaErioer/shuttle/blob/master/init/mysql/shuttle.sql

**Comment by CrushDemo01** [comment]
原来在这里！感谢！
